### ISSUE TITLE
Inactive status missing from response schema for GET /contract endpoint

### ISSUE THREAD

**Issue by mcshaman** [EazyCollectServices/EazyCollectAPIv3#2]
Just noticed you added the [response schema for the GET /contract endpoint](https://github.com/EazyCollectServices/EazyCollectAPIv3/commit/6dd47f7d1864ab3b66b0d74e484fd3bf25f6b2f8). Looks like you have missed the "Inactive" status from the Status enum.

> Upon creation, a Contract Status will read ”Inactive” and it will remain in this state until approximately 8-9 working days before either (a) the start date provided in the create contract call when creating an ad-hoc contract call or (b) the first payment date in the case of scheduled/recurring payments...

**Comment by EazyCollect** [comment]
@eazyJoe Could you please take a look?

**Comment by EazyCollect** [comment]
@mcshaman Joe has updated the docs.
